# Generated by Django 5.1.2 on 2024-10-29 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_publicacao',
            new_name='data_fotografia',
        ),
    ]
